version: 1.0.0.{build}
skip_tags: true

install:
- choco install -y nuget.commandline curl jq
- choco install wixtoolset -y -version 3.10.0.2103

build_script:
#- bash -c 'grep "submodule " .gitmodules  | cut -d'"'"'"'"'"' -f2 | xargs -P20 -L1 git submodule update --init --recursive' || true
- git submodule update --init --recursive
- nuget restore VATRP.sln
- set vatrpVersion=%APPVEYOR_BUILD_VERSION%
- set vatrpConfiguration="Release"
- dir "C:\Program Files\"
- dir "C:\Program Files (x86)\"
- powershell .\submodules\linphone-windows-dependencies\install.ps1
- python prepare.py -C
- python .\prepare.py -DENABLE_UNIT_TESTS=OFF -DENABLE_NON_FREE_CODECS=ON -DENABLE_H263=ON -DENABLE_OPENH264=ON -DENABLE_WEBRTC_AEC=ON -DENABLE_VCARD=ON -DCMAKE_VERBOSE_MAKEFILE=ON
- devenv .\WORK\cmake\Project.sln /build
- msbuild VATRP.sln /p:Configuration=%vatrpConfiguration%  /p:Targets="Build" /p:BuildInParallel=true /m
- set PATH="C:\Program Files (x86)\WiX Toolset v3.10\bin";%PATH%
- Candle -dVATRP.Version=%vatrpVersion% -dConfiguration=%vatrpConfiguration% -dOutDir=.\Setup\Out -dPlatform=x86 -dTargetDir=.\Setup\Out -dTargetExt=.msi -out .\Setup\obj\ -arch x86 -ext WixNetFxExtension.dll -ext WixUtilExtension.dll -ext WixUIExtension.dll .\Setup\ACE-Setup.wxs
- Light -out .\Setup\Out\ACE_Setup_%vatrpVersion%.msi -pdbout .\Setup\obj\ACE_Setup.wixpdb -cultures:null -ext WixNetFxExtension.dll -ext WixUtilExtension.dll -ext WixUIExtension.dll -contentsfile .\Setup\obj\ACE-Setup.wixproj.BindContentsFileListnull.txt -outputsfile .\Setup\obj\ACE-Setup.wixproj.BindOutputsFileListnull.txt -builtoutputsfile .\Setup\obj\ACE-Setup.wixproj.BindBuiltOutputsFileListnull.txt  .\Setup\obj\ACE-Setup.wixobj
- rd /S /Q .\Setup\obj

on_success:
- powershell -NoProfile -ExecutionPolicy Bypass .\Setup\HockeyApp.ps1

artifacts:
- path: Setup\Out\*.msi
  name: Setup

deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: Appveyor Automated v$(APPVEYOR_BUILD_VERSION)
  description: Release of version $(APPVEYOR_BUILD_VERSION) \n $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: 85zYs73xAspqCTY0Y19QCKgVZRrq1NuJ9LCLJx/rZ59vo00jRf2Rs6k81WYAj0yx
  prerelease: true
  on:
    branch: master
notifications:
- provider: Email
  to:
  - vatrp@vtcsecure.flowdock.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
